---
- name: VMware Snapshot with Automatic VM Discovery
  hosts: all
  gather_facts: no
  connection: local
  serial: 5
  
  vars:
    snapshot_name: "Snapshot for patching"
    snapshot_desc: "Created by Ansible via AWX for Patching Maintenance"
    safety_margin_gb: 10
    
    vcenter_hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') }}"
    vcenter_username: "{{ lookup('env', 'VCENTER_USERNAME') }}"
    vcenter_password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"

  tasks:
    # =========================================================================
    # STEP 1: FIND VM ACROSS ALL DATACENTERS (NO DATACENTER FILTER)
    # =========================================================================
    - name: Search for VM across all datacenters and folders
      community.vmware.vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        vm_type: vm
      delegate_to: localhost
      register: all_vms_info
      ignore_errors: yes

    - name: Check if VM search succeeded
      block:
        - debug:
            msg:
              - "=========================================="
              - "✗ ERROR: Failed to query VMs from vCenter"
              - "=========================================="
              - "Cannot search for VMs"
              - "Check vCenter credentials and connectivity"
              - "=========================================="
        - meta: end_host
      when: all_vms_info is failed

    # =========================================================================
    # STEP 2: FIND THE SPECIFIC VM BY NAME
    # =========================================================================
    - name: Filter to find our target VM
      set_fact:
        target_vm: "{{ all_vms_info.virtual_machines | selectattr('guest_name', 'equalto', inventory_hostname) | list | first | default(None) }}"
      when: all_vms_info.virtual_machines is defined

    - name: Check if VM was found
      block:
        - debug:
            msg:
              - "=========================================="
              - "✗ VM NOT FOUND"
              - "=========================================="
              - "VM Name: {{ inventory_hostname }}"
              - "vCenter: {{ vcenter_hostname }}"
              - ""
              - "This VM does not exist in any datacenter"
              - "or the service account cannot see it."
              - ""
              - "Total VMs visible: {{ all_vms_info.virtual_machines | length }}"
              - "=========================================="
        - meta: end_host
      when: target_vm is none or target_vm == None

    - name: Display discovered VM information
      debug:
        msg:
          - "=========================================="
          - "✓ VM FOUND"
          - "=========================================="
          - "VM Name      : {{ target_vm.guest_name }}"
          - "UUID         : {{ target_vm.uuid }}"
          - "Power State  : {{ target_vm.power_state }}"
          - "Datacenter   : {{ target_vm.datacenter }}"
          - "Folder       : {{ target_vm.vm_folder }}"
          - "Cluster      : {{ target_vm.cluster | default('N/A') }}"
          - "=========================================="

    # =========================================================================
    # STEP 3: GET DETAILED VM INFO USING UUID (WORKS ACROSS ALL DATACENTERS)
    # =========================================================================
    - name: Get detailed VM information using UUID
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        uuid: "{{ target_vm.uuid }}"
        schema: vsphere
      delegate_to: localhost
      register: vm_info
      ignore_errors: yes

    - name: Check VM detailed info retrieval
      block:
        - debug:
            msg: "✗ Failed to retrieve detailed VM info for {{ inventory_hostname }}"
        - meta: end_host
      when: vm_info is failed or vm_info.instance is not defined

    # =========================================================================
    # STEP 4: EXTRACT VM FACTS
    # =========================================================================
    - name: Set VM basic facts
      set_fact:
        vm_moid: "{{ vm_info.instance._vimref.split(':')[1] }}"
        vm_name: "{{ vm_info.instance.name }}"
        vm_power_state: "{{ vm_info.instance.runtime.powerState }}"
        is_powered_on: "{{ vm_info.instance.runtime.powerState == 'poweredOn' }}"
        vm_datacenter: "{{ target_vm.datacenter }}"
        vm_folder: "{{ target_vm.vm_folder }}"

    - name: Display VM operational info
      debug:
        msg:
          - "VM: {{ vm_name }}"
          - "MOID: {{ vm_moid }}"
          - "Datacenter: {{ vm_datacenter }}"
          - "Folder: {{ vm_folder }}"
          - "Power: {{ vm_power_state }}"

    # Check power state
    - name: Skip if powered off
      block:
        - debug:
            msg: "⊘ SKIPPED: {{ vm_name }} is powered off"
        - meta: end_host
      when: not is_powered_on

    # =========================================================================
    # STEP 5: CHECK FOR EXISTING SNAPSHOTS
    # =========================================================================
    - name: Check for existing snapshots
      set_fact:
        has_existing_snapshot: "{{ vm_info.instance.snapshot is defined and vm_info.instance.snapshot.rootSnapshotList is defined and vm_info.instance.snapshot.rootSnapshotList | length > 0 }}"

    - name: Skip if snapshot already exists
      block:
        - debug:
            msg:
              - "=========================================="
              - "⊘ SKIPPED: Snapshot already exists"
              - "VM: {{ vm_name }}"
              - "Datacenter: {{ vm_datacenter }}"
              - "Existing snapshots: {{ vm_info.instance.snapshot.rootSnapshotList | length }}"
              - "=========================================="
        - meta: end_host
      when: has_existing_snapshot

    # =========================================================================
    # STEP 6: EXTRACT STORAGE INFO
    # =========================================================================
    - name: Check if storage info is available
      set_fact:
        has_storage_info: "{{ vm_info.instance.storage is defined and vm_info.instance.storage.perDatastoreUsage is defined }}"

    - name: Extract VM storage information
      set_fact:
        vm_storage_per_ds: "{{ vm_info.instance.storage.perDatastoreUsage | default([]) }}"
        vm_datastore_names: "{{ vm_info.instance.config.datastoreUrl | map(attribute='name') | list }}"
        vm_datastore_refs: "{{ vm_info.instance.datastore }}"
        vm_total_committed_bytes: "{{ vm_info.instance.storage.perDatastoreUsage | map(attribute='committed') | sum }}"
      when: has_storage_info

    - name: Calculate total VM storage
      set_fact:
        vm_total_committed_gb: "{{ (vm_total_committed_bytes | int / 1073741824) | round(2) }}"
      when: has_storage_info

    - name: Fail if storage info unavailable
      block:
        - debug:
            msg:
              - "=========================================="
              - "✗ ERROR: Cannot retrieve VM storage information"
              - "=========================================="
              - "VM: {{ vm_name }}"
              - "Storage information is required for space check"
              - "Cannot proceed without storage data"
              - "=========================================="
        - fail:
            msg: "VM storage information unavailable - space check is mandatory"
      when: not has_storage_info

    - name: Display VM total storage
      debug:
        msg: 
          - "VM Total Committed Storage: {{ vm_total_committed_gb }} GB"
          - "VM uses {{ vm_storage_per_ds | length }} datastore(s)"
          - "Datastores: {{ vm_datastore_names | join(', ') }}"

    # =========================================================================
    # STEP 7: GET DATASTORE DETAILS (GLOBAL QUERY)
    # =========================================================================
    - name: Get all datastores from vCenter
      community.vmware.vmware_datastore_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
      delegate_to: localhost
      register: all_datastores_info
      ignore_errors: yes

    - name: Check datastore info retrieval
      block:
        - debug:
            msg:
              - "=========================================="
              - "✗ ERROR: Failed to retrieve datastore information"
              - "=========================================="
              - "Cannot query datastores from vCenter"
              - "Space check cannot be performed"
              - "=========================================="
        - fail:
            msg: "Datastore query failed - space check is mandatory"
      when: all_datastores_info is failed or all_datastores_info.datastores is not defined

    # =========================================================================
    # STEP 8: BUILD DATASTORE MAPPING
    # =========================================================================
    - name: Trim whitespace from VM datastore names
      set_fact:
        vm_datastore_names_clean: "{{ vm_datastore_names | map('trim') | list }}"

    - name: Filter datastores used by VM
      set_fact:
        vm_datastores: "{{ all_datastores_info.datastores | selectattr('name', 'in', vm_datastore_names_clean) | list }}"

    - name: Debug filtered datastores
      debug:
        msg:
          - "Found {{ vm_datastores | length }} matching datastore(s)"
          - "VM uses: {{ vm_datastore_names_clean | join(', ') }}"

    - name: Fail if no datastores matched
      block:
        - debug:
            msg:
              - "=========================================="
              - "✗ ERROR: DATASTORE MISMATCH"
              - "=========================================="
              - "VM: {{ vm_name }}"
              - "VM reports datastores: {{ vm_datastore_names_clean | join(', ') }}"
              - "vCenter: {{ vcenter_hostname }}"
              - "Found: 0 matching datastores"
              - ""
              - "Total datastores visible: {{ all_datastores_info.datastores | length }}"
              - ""
              - "Possible causes:"
              - "1. Datastore names don't match exactly"
              - "2. Permission issues - service account cannot see these datastores"
              - ""
              - "Cannot proceed without datastore information."
              - "=========================================="
        - fail:
            msg: "Cannot find VM datastores in vCenter query - space check is mandatory"
      when: vm_datastores | length == 0

    - name: Build datastore mapping
      set_fact:
        ds_name_to_details: {}

    - name: Populate datastore details
      set_fact:
        ds_name_to_details: >-
          {{
            ds_name_to_details | combine({
              item.name: {
                'free_gb': (item.freeSpace / 1073741824) | round(2),
                'capacity_gb': (item.capacity / 1073741824) | round(2)
              }
            })
          }}
      loop: "{{ vm_datastores }}"
      loop_control:
        label: "{{ item.name }}"

    # =========================================================================
    # STEP 9: ANALYZE DATASTORE SPACE
    # =========================================================================
    - name: Calculate required space for snapshot
      set_fact:
        required_snapshot_space_gb: "{{ ((vm_total_committed_gb | float) + (safety_margin_gb | float)) | round(2) | float }}"

    - name: Create datastore checks list
      set_fact:
        datastore_checks: []

    - name: Build datastore check information
      set_fact:
        datastore_checks: >-
          {{
            datastore_checks + [{
              'name': item,
              'ds_free_gb': ds_name_to_details[item]['free_gb'],
              'ds_capacity_gb': ds_name_to_details[item]['capacity_gb'],
              'has_space': (ds_name_to_details[item]['free_gb'] | float) >= (required_snapshot_space_gb | float)
            }]
          }}
      loop: "{{ vm_datastore_names_clean }}"
      loop_control:
        label: "{{ item }}"
      when: 
        - ds_name_to_details is defined
        - item in ds_name_to_details

    - name: Display datastore space analysis
      debug:
        msg: |
          ==========================================
          Datastore Space Analysis for {{ vm_name }}
          ==========================================
          Datacenter: {{ vm_datacenter }}
          Folder: {{ vm_folder }}
          
          VM Total Storage        : {{ vm_total_committed_gb }} GB
          Required for Snapshot   : {{ required_snapshot_space_gb }} GB (VM storage + {{ safety_margin_gb }} GB margin)
          
          Checking if ANY datastore has >= {{ required_snapshot_space_gb }} GB free space:
          ---
          {% for ds in datastore_checks %}
          Datastore: {{ ds.name }}
            DS Free Space  : {{ ds.ds_free_gb }} GB
            DS Capacity    : {{ ds.ds_capacity_gb }} GB
            Can fit VM?    : {{ '✓ YES - This datastore can hold the snapshot' if ds.has_space else '✗ NO - Free space < ' ~ required_snapshot_space_gb ~ ' GB' }}
          ---
          {% endfor %}
          ==========================================

    - name: Check if AT LEAST ONE datastore has sufficient space
      set_fact:
        datastores_with_space: "{{ datastore_checks | selectattr('has_space', 'equalto', true) | list }}"

    - name: Fail if NO datastore has sufficient space
      block:
        - debug:
            msg: |
              ==========================================
              ✗ INSUFFICIENT SPACE - SNAPSHOT BLOCKED
              ==========================================
              VM: {{ vm_name }}
              Datacenter: {{ vm_datacenter }}
              VM Total Storage: {{ vm_total_committed_gb }} GB
              Required Space  : {{ required_snapshot_space_gb }} GB
              
              Reason: NO datastore has enough free space to hold the entire VM snapshot.
              
              Datastore free space summary:
              {% for ds in datastore_checks %}
              
              {{ ds.name }}:
                Free Space : {{ ds.ds_free_gb }} GB
                Shortage   : {{ ((required_snapshot_space_gb | float) - (ds.ds_free_gb | float)) | round(2) }} GB
              {% endfor %}
              
              At least ONE datastore needs {{ required_snapshot_space_gb }} GB free space.
              Cannot proceed with snapshot creation.
              ==========================================
        - fail:
            msg: "Insufficient datastore space - snapshot creation blocked"
      when: datastores_with_space | length == 0

    - name: Space check passed
      debug:
        msg: |
          ==========================================
          ✓ SPACE CHECK PASSED
          ==========================================
          VM: {{ vm_name }}
          Datacenter: {{ vm_datacenter }}
          Folder: {{ vm_folder }}
          Total VM Storage: {{ vm_total_committed_gb }} GB
          Required Space  : {{ required_snapshot_space_gb }} GB
          
          {{ datastores_with_space | length }} datastore(s) have sufficient space:
          {% for ds in datastores_with_space %}
          - {{ ds.name }}: {{ ds.ds_free_gb }} GB free
          {% endfor %}
          
          Proceeding with snapshot creation...
          ==========================================

    # =========================================================================
    # STEP 10: CREATE SNAPSHOT USING UUID (WORKS ACROSS ALL DATACENTERS)
    # =========================================================================
    - name: Create VM snapshot using UUID
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        uuid: "{{ target_vm.uuid }}"
        state: present
        snapshot_name: "{{ snapshot_name }}"
        description: "{{ snapshot_desc }}"
        quiesce: no
        memory_dump: no
      delegate_to: localhost
      register: snapshot_result
      ignore_errors: yes

    # =========================================================================
    # STEP 11: REPORT RESULTS
    # =========================================================================
    - name: Report snapshot success
      debug:
        msg:
          - "=========================================="
          - "✓ SNAPSHOT CREATED SUCCESSFULLY"
          - "=========================================="
          - "VM: {{ vm_name }}"
          - "Datacenter: {{ vm_datacenter }}"
          - "Folder: {{ vm_folder }}"
          - "Snapshot Name: {{ snapshot_name }}"
          - "VM Total Storage: {{ vm_total_committed_gb }} GB"
          - "UUID: {{ target_vm.uuid }}"
          - "=========================================="
      when: snapshot_result is succeeded

    - name: Report snapshot failure
      debug:
        msg:
          - "=========================================="
          - "✗ SNAPSHOT CREATION FAILED"
          - "=========================================="
          - "VM: {{ vm_name }}"
          - "Datacenter: {{ vm_datacenter }}"
          - "Folder: {{ vm_folder }}"
          - "UUID: {{ target_vm.uuid }}"
          - "Error: {{ snapshot_result.msg | default('Unknown error') }}"
          - "=========================================="
      when: snapshot_result is failed

    - name: Fail the host if snapshot creation failed
      fail:
        msg: "Snapshot creation failed for {{ vm_name }}"
      when: snapshot_result is failed
