- name: Diagnostic Check
  hosts: all
  gather_facts: no
  connection: local
  tasks:
    - name: Get VM details
      community.vmware.vmware_guest_info:
        hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') }}"
        username: "{{ lookup('env', 'VCENTER_USERNAME') }}"
        password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"
        validate_certs: no
        datacenter: "{{ lookup('env', 'VCENTER_DATACENTER') }}"
        name: "{{ inventory_hostname }}"
      delegate_to: localhost
      register: vm_info
    
    - debug:
        msg:
          - "VM Name: {{ vm_info.instance.hw_name }}"
          - "VM UUID: {{ vm_info.instance.hw_product_uuid }}"
          - "VM Folder: {{ vm_info.instance.hw_folder }}"
          - "Power State: {{ vm_info.instance.hw_power_status }}"
