---
- name: Snapshot Diagnostic Test
  hosts: all
  gather_facts: no
  connection: local

  vars:
    vcenter_hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') }}"
    vcenter_username: "{{ lookup('env', 'VCENTER_USERNAME') }}"
    vcenter_password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"
    datacenter_name: "{{ lookup('env', 'VCENTER_DATACENTER') }}"

  tasks:
    - name: Get VM Info
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        name: "{{ inventory_hostname }}"
      delegate_to: localhost
      register: vm_info

    - name: Display VM Details
      debug:
        msg:
          - "=========================================="
          - "VM Name       : {{ vm_info.instance.hw_name }}"
          - "VM UUID       : {{ vm_info.instance.hw_product_uuid }}"
          - "VM Folder     : {{ vm_info.instance.hw_folder | default('N/A') }}"
          - "Power State   : {{ vm_info.instance.hw_power_status }}"
          - "Guest OS      : {{ vm_info.instance.hw_guest_id }}"
          - "VMware Tools  : {{ vm_info.instance.guest_tools_status | default('N/A') }}"
          - "Is Template   : {{ vm_info.instance.hw_is_template | default(false) }}"
          - "=========================================="

    - name: Test Snapshot Creation (Method 1 - UUID)
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        uuid: "{{ vm_info.instance.hw_product_uuid }}"
        state: present
        snapshot_name: "TEST_SNAPSHOT_{{ ansible_date_time.epoch }}"
        description: "Diagnostic test snapshot"
        quiesce: no
        memory_dump: no
      delegate_to: localhost
      register: snapshot_uuid
      ignore_errors: yes

    - name: Display Method 1 Result
      debug:
        msg:
          - "Method 1 (UUID): {{ 'SUCCESS ✓' if snapshot_uuid.changed else 'FAILED ✗' }}"
          - "{{ snapshot_uuid.msg | default('') }}"

    - name: Test Snapshot Creation (Method 2 - Name Only)
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        name: "{{ inventory_hostname }}"
        state: present
        snapshot_name: "TEST_SNAPSHOT_{{ ansible_date_time.epoch }}"
        description: "Diagnostic test snapshot"
        quiesce: no
        memory_dump: no
      delegate_to: localhost
      register: snapshot_name
      ignore_errors: yes
      when: snapshot_uuid.failed | default(false)

    - name: Display Method 2 Result
      debug:
        msg:
          - "Method 2 (Name): {{ 'SUCCESS ✓' if snapshot_name.changed else 'FAILED ✗' }}"
          - "{{ snapshot_name.msg | default('') }}"
      when: snapshot_name is defined

    - name: Final Diagnostic Summary
      debug:
        msg:
          - "=========================================="
          - "DIAGNOSTIC COMPLETE"
          - "UUID Method   : {{ 'WORKS ✓' if snapshot_uuid.changed else 'FAILS ✗' }}"
          - "Name Method   : {{ 'WORKS ✓' if (snapshot_name is defined and snapshot_name.changed) else 'FAILS ✗' if snapshot_name is defined else 'NOT TESTED' }}"
          - ""
          - "Errors:"
          - "{{ snapshot_uuid.msg | default('None') }}"
          - "{{ snapshot_name.msg | default('None') if snapshot_name is defined else '' }}"
          - "=========================================="
