---
- name: VMware Snapshot Creation with Storage Validation
  hosts: all
  gather_facts: no
  connection: local
  
  vars:
    snapshot_name: "Snapshot for patching"
    snapshot_desc: "Created by Ansible via AWX for Patching Maintenance"
    safety_margin_gb: 10  # Extra GB to keep free as safety buffer
    
    vcenter_hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') }}"
    vcenter_username: "{{ lookup('env', 'VCENTER_USERNAME') }}"
    vcenter_password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"
    datacenter_name: "{{ lookup('env', 'VCENTER_DATACENTER') }}"

  tasks:
    # -------------------------------------------------------------------------
    # STEP 1: GET VM INFO (INCLUDING MOID AND STORAGE)
    # -------------------------------------------------------------------------
    - name: Get VM information
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        name: "{{ inventory_hostname }}"
        schema: vsphere
      delegate_to: localhost
      register: vm_info

    # -------------------------------------------------------------------------
    # STEP 2: EXTRACT VM STORAGE USAGE
    # -------------------------------------------------------------------------
    - name: Set VM facts
      set_fact:
        vm_moid: "{{ vm_info.instance.moid }}"
        is_powered_on: "{{ vm_info.instance.hw_power_status == 'poweredOn' }}"
        vm_datastores: "{{ vm_info.instance.hw_datastore }}"
        # Get actual committed storage in GB (this is what's really used)
        vm_storage_committed_gb: "{{ (vm_info.instance.storage.committed | default(0) / 1024 / 1024 / 1024) | round(2) }}"
        # Get uncommitted storage (thin provisioned space that could be used)
        vm_storage_uncommitted_gb: "{{ (vm_info.instance.storage.uncommitted | default(0) / 1024 / 1024 / 1024) | round(2) }}"

    - name: Display VM storage information
      debug:
        msg:
          - "=========================================="
          - "VM Storage Analysis: {{ inventory_hostname }}"
          - "=========================================="
          - "MOID                : {{ vm_moid }}"
          - "Power State         : {{ vm_info.instance.hw_power_status }}"
          - "Datastores          : {{ vm_datastores | join(', ') }}"
          - "Committed Storage   : {{ vm_storage_committed_gb }} GB (actual usage)"
          - "Uncommitted Storage : {{ vm_storage_uncommitted_gb }} GB (thin prov)"
          - "Total Potential     : {{ (vm_storage_committed_gb | float + vm_storage_uncommitted_gb | float) | round(2) }} GB"
          - "=========================================="

    # -------------------------------------------------------------------------
    # STEP 3: CHECK DATASTORE FREE SPACE FOR EACH DATASTORE
    # -------------------------------------------------------------------------
    - name: Get datastore information for all VM datastores
      community.vmware.vmware_datastore_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        name: "{{ item }}"
      delegate_to: localhost
      register: datastore_info
      loop: "{{ vm_datastores }}"

    # -------------------------------------------------------------------------
    # STEP 4: CALCULATE SPACE REQUIREMENTS AND VALIDATE
    # -------------------------------------------------------------------------
    - name: Calculate space requirements
      set_fact:
        # Snapshot needs approximately the committed storage size
        # (delta disks will grow based on changes)
        required_space_gb: "{{ (vm_storage_committed_gb | float + safety_margin_gb | float) | round(2) }}"

    - name: Check if all datastores have sufficient space
      set_fact:
        datastore_checks: >-
          {{
            datastore_info.results | map(attribute='datastores') | flatten |
            map('combine', {'has_space': (item.freeSpace / 1024 / 1024 / 1024) > (required_space_gb | float)}) |
            list
          }}

    - name: Display datastore space analysis
      debug:
        msg:
          - "=========================================="
          - "Datastore Space Analysis"
          - "=========================================="
          - "Required Space      : {{ required_space_gb }} GB"
          - "  (VM Usage: {{ vm_storage_committed_gb }} GB + Safety: {{ safety_margin_gb }} GB)"
          - "---"
          - "{% for ds in datastore_checks %}"
          - "Datastore: {{ ds.name }}"
          - "  Capacity   : {{ (ds.capacity / 1024 / 1024 / 1024) | round(2) }} GB"
          - "  Free Space : {{ (ds.freeSpace / 1024 / 1024 / 1024) | round(2) }} GB"
          - "  Status     : {{ '✓ SUFFICIENT' if ds.has_space else '✗ INSUFFICIENT' }}"
          - "{% endfor %}"
          - "=========================================="

    - name: Determine if snapshot can proceed
      set_fact:
        can_create_snapshot: "{{ datastore_checks | selectattr('has_space', 'equalto', true) | list | length > 0 }}"

    # -------------------------------------------------------------------------
    # STEP 5: CREATE SNAPSHOT (ONLY IF SPACE IS AVAILABLE)
    # -------------------------------------------------------------------------
    - name: Create VM snapshot using MOID
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        moid: "{{ vm_moid }}"
        state: present
        snapshot_name: "{{ snapshot_name }}"
        description: "{{ snapshot_desc }}"
        quiesce: no
        memory_dump: no
      delegate_to: localhost
      when:
        - is_powered_on
        - can_create_snapshot
      register: snapshot_result

    # -------------------------------------------------------------------------
    # STEP 6: REPORT RESULTS
    # -------------------------------------------------------------------------
    - name: Report snapshot creation success
      debug:
        msg:
          - "=========================================="
          - "✓ SUCCESS"
          - "Snapshot '{{ snapshot_name }}' created for {{ inventory_hostname }}"
          - "VM Storage: {{ vm_storage_committed_gb }} GB"
          - "Snapshot will use delta disks on datastores"
          - "=========================================="
      when:
        - snapshot_result is defined
        - snapshot_result.changed

    - name: Report snapshot creation failure
      debug:
        msg:
          - "=========================================="
          - "✗ FAILED"
          - "Could not create snapshot for {{ inventory_hostname }}"
          - "Error: {{ snapshot_result.msg | default('Unknown error') }}"
          - "=========================================="
      when:
        - snapshot_result is defined
        - snapshot_result.failed | default(false)

    - name: Report skipped (VM powered off)
      debug:
        msg:
          - "=========================================="
          - "⊘ SKIPPED - VM Powered Off"
          - "{{ inventory_hostname }} is powered off"
          - "=========================================="
      when: not is_powered_on

    - name: Report skipped (insufficient datastore space)
      debug:
        msg:
          - "=========================================="
          - "⊘ SKIPPED - Insufficient Datastore Space"
          - "{{ inventory_hostname }} snapshot requires {{ required_space_gb }} GB"
          - "NONE of the datastores have sufficient free space:"
          - "{% for ds in datastore_checks %}"
          - "  - {{ ds.name }}: {{ (ds.freeSpace / 1024 / 1024 / 1024) | round(2) }} GB free (need {{ required_space_gb }} GB)"
          - "{% endfor %}"
          - "=========================================="
      when:
        - is_powered_on
        - not can_create_snapshot
