---
- name: VMware Snapshot Creation with Storage Validation
  hosts: all
  gather_facts: no
  connection: local
  serial: 5
  
  vars:
    snapshot_name: "Snapshot for patching"
    snapshot_desc: "Created by Ansible via AWX for Patching Maintenance"
    safety_margin_gb: 10
    
    vcenter_hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') }}"
    vcenter_username: "{{ lookup('env', 'VCENTER_USERNAME') }}"
    vcenter_password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"
    datacenter_name: "{{ lookup('env', 'VCENTER_DATACENTER') }}"

  tasks:
    # -------------------------------------------------------------------------
    # STEP 1: GET VM INFO WITH VSPHERE SCHEMA
    # -------------------------------------------------------------------------
    - name: Get VM information with vSphere schema
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        name: "{{ inventory_hostname }}"
        schema: vsphere
      delegate_to: localhost
      register: vm_info
      ignore_errors: yes

    - name: Check VM info retrieval
      block:
        - debug:
            msg: "✗ Failed to retrieve VM info for {{ inventory_hostname }}"
        - meta: end_host
      when: vm_info is failed or vm_info.instance is not defined

    # -------------------------------------------------------------------------
    # STEP 2: EXTRACT VM BASIC INFO
    # -------------------------------------------------------------------------
    - name: Set VM basic facts
      set_fact:
        vm_moid: "{{ vm_info.instance._vimref.split(':')[1] }}"
        vm_name: "{{ vm_info.instance.name }}"
        vm_power_state: "{{ vm_info.instance.runtime.powerState }}"
        is_powered_on: "{{ vm_info.instance.runtime.powerState == 'poweredOn' }}"

    - name: Display VM basic info
      debug:
        msg:
          - "VM: {{ vm_name }}"
          - "MOID: {{ vm_moid }}"
          - "Power: {{ vm_power_state }}"

    # Check power state
    - name: Skip if powered off
      block:
        - debug:
            msg: "⊘ SKIPPED: {{ vm_name }} is powered off"
        - meta: end_host
      when: not is_powered_on

    # -------------------------------------------------------------------------
    # STEP 3: EXTRACT STORAGE INFO FROM VSPHERE DATA
    # -------------------------------------------------------------------------
    - name: Check if storage info is available
      set_fact:
        has_storage_info: "{{ vm_info.instance.storage is defined and vm_info.instance.storage.committed is defined }}"

    - name: Extract VM storage information
      set_fact:
        vm_total_committed_bytes: "{{ vm_info.instance.storage.committed }}"
        vm_total_uncommitted_bytes: "{{ vm_info.instance.storage.uncommitted | default(0) }}"
        vm_storage_per_ds: "{{ vm_info.instance.storage.perDatastoreUsage | default([]) }}"
      when: has_storage_info

    - name: Use fallback if storage info unavailable
      set_fact:
        vm_total_committed_bytes: 0
        vm_total_uncommitted_bytes: 0
        vm_storage_per_ds: []
        skip_space_check: true
      when: not has_storage_info

    - name: Convert storage to GB
      set_fact:
        vm_committed_gb: "{{ (vm_total_committed_bytes | int / 1073741824) | round(2) }}"
        vm_uncommitted_gb: "{{ (vm_total_uncommitted_bytes | int / 1073741824) | round(2) }}"

    - name: Calculate required space per snapshot
      set_fact:
        required_space_gb: "{{ (vm_committed_gb | float + safety_margin_gb | float) | round(2) }}"

    - name: Display VM storage summary
      debug:
        msg:
          - "=========================================="
          - "VM Storage Summary: {{ vm_name }}"
          - "=========================================="
          - "Committed Storage  : {{ vm_committed_gb }} GB"
          - "Uncommitted Storage: {{ vm_uncommitted_gb }} GB"
          - "Required for Snapshot: {{ required_space_gb }} GB"
          - "Number of Datastores: {{ vm_storage_per_ds | length }}"
          - "{{ '⚠ Storage info unavailable - using estimates' if not has_storage_info else '' }}"

    # -------------------------------------------------------------------------
    # STEP 4: GET DATASTORE DETAILS
    # -------------------------------------------------------------------------
    - name: Get all datastores in datacenter
      community.vmware.vmware_datastore_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
      delegate_to: localhost
      register: all_datastores_info
      ignore_errors: yes

    - name: Check datastore info retrieval
      set_fact:
        skip_space_check: true
      when: all_datastores_info is failed or all_datastores_info.datastores is not defined

    # -------------------------------------------------------------------------
    # STEP 5: ANALYZE DATASTORE SPACE
    # -------------------------------------------------------------------------
    - name: Analyze datastore space availability
      block:
        - name: Build datastore analysis list
          set_fact:
            ds_refs: "{{ vm_storage_per_ds | map(attribute='datastore') | list }}"

        - name: Extract datastore IDs from vim references
          set_fact:
            ds_ids: "{{ ds_refs | map('regex_replace', '^vim\\.Datastore:', '') | list }}"

        - name: Create datastore space check list
          set_fact:
            datastore_checks: []

        - name: Build detailed datastore information
          set_fact:
            datastore_checks: >-
              {{
                datastore_checks + [{
                  'name': item.name,
                  'free_gb': (item.freeSpace / 1073741824) | round(2),
                  'capacity_gb': (item.capacity / 1073741824) | round(2),
                  'has_space': ((item.freeSpace / 1073741824) | float) >= (required_space_gb | float)
                }]
              }}
          loop: "{{ all_datastores_info.datastores | selectattr('name', 'in', vm_info.instance.datastore | map(attribute='name') | list) | list }}"
          loop_control:
            label: "{{ item.name }}"
          when: vm_info.instance.datastore is defined

        - name: Display datastore space analysis
          debug:
            msg:
              - "=========================================="
              - "Datastore Space Analysis"
              - "=========================================="
              - "Required Space: {{ required_space_gb }} GB"
              - "---"
              - "{% for ds in datastore_checks %}"
              - "{{ ds.name }}:"
              - "  Capacity  : {{ ds.capacity_gb }} GB"
              - "  Free Space: {{ ds.free_gb }} GB"
              - "  Status    : {{ '✓ SUFFICIENT' if ds.has_space else '✗ INSUFFICIENT' }}"
              - "{% endfor %}"
              - "=========================================="

        - name: Check if ANY datastore has sufficient space
          set_fact:
            can_create_snapshot: "{{ datastore_checks | selectattr('has_space', 'equalto', true) | list | length > 0 }}"

        - name: Skip if no space available
          block:
            - debug:
                msg:
                  - "⊘ SKIPPED: No datastore has sufficient space"
                  - "Required: {{ required_space_gb }} GB"
                  - "NONE of the {{ datastore_checks | length }} datastores have enough space"
            - meta: end_host
          when: not can_create_snapshot

      when: skip_space_check is not defined

    - name: Warning if space check skipped
      debug:
        msg: "⚠ WARNING: Datastore space check skipped, proceeding anyway"
      when: skip_space_check is defined

    # -------------------------------------------------------------------------
    # STEP 6: CREATE SNAPSHOT
    # -------------------------------------------------------------------------
    - name: Create VM snapshot using MOID
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        moid: "{{ vm_moid }}"
        state: present
        snapshot_name: "{{ snapshot_name }}"
        description: "{{ snapshot_desc }}"
        quiesce: no
        memory_dump: no
      delegate_to: localhost
      register: snapshot_result
      ignore_errors: yes

    # -------------------------------------------------------------------------
    # STEP 7: REPORT RESULTS
    # -------------------------------------------------------------------------
    - name: Report snapshot success
      debug:
        msg:
          - "=========================================="
          - "✓ SUCCESS"
          - "VM: {{ vm_name }}"
          - "Snapshot: '{{ snapshot_name }}' created"
          - "VM Storage: {{ vm_committed_gb }} GB"
          - "=========================================="
      when:
        - snapshot_result is defined
        - not (snapshot_result is failed)
        - snapshot_result.changed | default(false)

    - name: Report snapshot failure
      debug:
        msg:
          - "=========================================="
          - "✗ FAILED"
          - "VM: {{ vm_name }}"
          - "Error: {{ snapshot_result.msg | default('Snapshot creation failed') }}"
          - "=========================================="
      when:
        - snapshot_result is defined
        - snapshot_result is failed

    - name: Report no change
      debug:
        msg:
          - "=========================================="
          - "⊘ NO CHANGE"
          - "VM: {{ vm_name }}"
          - "Snapshot may already exist"
          - "=========================================="
      when:
        - snapshot_result is defined
        - not (snapshot_result is failed)
        - not (snapshot_result.changed | default(false))
