---
- name: VMware Snapshot Creation with Storage Validation (Fixed)
  hosts: all
  gather_facts: no
  connection: local
  serial: 5
  
  vars:
    snapshot_name: "Snapshot for patching"
    snapshot_desc: "Created by Ansible via AWX for Patching Maintenance"
    safety_margin_gb: 10
    
    vcenter_hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') }}"
    vcenter_username: "{{ lookup('env', 'VCENTER_USERNAME') }}"
    vcenter_password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"
    datacenter_name: "{{ lookup('env', 'VCENTER_DATACENTER') }}"

  tasks:
    # -------------------------------------------------------------------------
    # STEP 1: GET VM INFO WITH VSPHERE SCHEMA (includes storage)
    # -------------------------------------------------------------------------
    - name: Get VM information with vSphere schema
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        name: "{{ inventory_hostname }}"
        schema: vsphere
      delegate_to: localhost
      register: vm_info
      ignore_errors: yes

    - name: Check VM info retrieval
      block:
        - debug:
            msg: "Failed to retrieve VM info for {{ inventory_hostname }}"
        - meta: end_host
      when: vm_info is failed or vm_info.instance is not defined

    # -------------------------------------------------------------------------
    # STEP 2: EXTRACT VM DETAILS
    # -------------------------------------------------------------------------
    - name: Set VM facts from response
      set_fact:
        vm_moid: "{{ vm_info.instance.moid }}"
        vm_power_state: "{{ vm_info.instance.hw_power_status }}"
        is_powered_on: "{{ vm_info.instance.hw_power_status == 'poweredOn' }}"
        vm_datastores: "{{ vm_info.instance.hw_datastores }}"

    - name: Calculate VM storage from files (accurate method)
      set_fact:
        vm_storage_bytes: "{{ vm_info.instance.hw_files | map(attribute='size') | map('int') | sum }}"
      when: vm_info.instance.hw_files is defined

    - name: Convert storage to GB
      set_fact:
        vm_storage_gb: "{{ (vm_storage_bytes | int / 1073741824) | round(2) }}"
      when: vm_storage_bytes is defined

    - name: Set default storage if calculation failed
      set_fact:
        vm_storage_gb: 150
      when: vm_storage_gb is not defined

    - name: Display VM information
      debug:
        msg:
          - "=========================================="
          - "VM: {{ inventory_hostname }}"
          - "MOID: {{ vm_moid }}"
          - "Power State: {{ vm_power_state }}"
          - "Datastores: {{ vm_datastores | join(', ') }}"
          - "Storage Used: {{ vm_storage_gb }} GB"
          - "=========================================="

    # -------------------------------------------------------------------------
    # STEP 3: CHECK POWER STATE
    # -------------------------------------------------------------------------
    - name: Skip if powered off
      block:
        - debug:
            msg: "⊘ SKIPPED: {{ inventory_hostname }} is powered off"
        - meta: end_host
      when: not is_powered_on

    # -------------------------------------------------------------------------
    # STEP 4: GET DATASTORE INFORMATION
    # -------------------------------------------------------------------------
    - name: Get all datastores in datacenter
      community.vmware.vmware_datastore_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
      delegate_to: localhost
      register: all_datastores
      ignore_errors: yes

    # -------------------------------------------------------------------------
    # STEP 5: ANALYZE SPACE ON VM'S DATASTORES
    # -------------------------------------------------------------------------
    - name: Check datastore space
      block:
        - name: Filter datastores used by this VM
          set_fact:
            vm_ds_details: "{{ all_datastores.datastores | selectattr('name', 'in', vm_datastores) | list }}"

        - name: Calculate required space with safety margin
          set_fact:
            required_space_gb: "{{ (vm_storage_gb | float + safety_margin_gb | float) | round(2) }}"

        - name: Build datastore analysis
          set_fact:
            ds_analysis: "{{ ds_analysis | default([]) + [{'name': item.name, 'free_gb': (item.freeSpace / 1073741824) | round(2), 'capacity_gb': (item.capacity / 1073741824) | round(2), 'has_space': (item.freeSpace / 1073741824) >= (required_space_gb | float)}] }}"
          loop: "{{ vm_ds_details }}"
          loop_control:
            label: "{{ item.name }}"

        - name: Display datastore space analysis
          debug:
            msg:
              - "Datastore Space Analysis:"
              - "Required: {{ required_space_gb }} GB (VM: {{ vm_storage_gb }} GB + Safety: {{ safety_margin_gb }} GB)"
              - "{% for ds in ds_analysis %}"
              - "  {{ ds.name }}:"
              - "    Capacity: {{ ds.capacity_gb }} GB"
              - "    Free: {{ ds.free_gb }} GB"
              - "    Status: {{ '✓ SUFFICIENT' if ds.has_space else '✗ INSUFFICIENT' }}"
              - "{% endfor %}"

        - name: Check if any datastore has sufficient space
          set_fact:
            can_create_snapshot: "{{ ds_analysis | selectattr('has_space', 'equalto', true) | list | length > 0 }}"

        - name: Skip if no space available
          block:
            - debug:
                msg:
                  - "⊘ SKIPPED: Insufficient Space"
                  - "No datastore has {{ required_space_gb }} GB free"
            - meta: end_host
          when: not can_create_snapshot

      when: 
        - all_datastores is defined
        - all_datastores is not failed
        - all_datastores.datastores is defined

    # -------------------------------------------------------------------------
    # STEP 6: CREATE SNAPSHOT
    # -------------------------------------------------------------------------
    - name: Create VM snapshot
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        moid: "{{ vm_moid }}"
        state: present
        snapshot_name: "{{ snapshot_name }}"
        description: "{{ snapshot_desc }}"
        quiesce: no
        memory_dump: no
      delegate_to: localhost
      register: snapshot_result
      ignore_errors: yes

    # -------------------------------------------------------------------------
    # STEP 7: REPORT RESULTS
    # -------------------------------------------------------------------------
    - name: Report success
      debug:
        msg:
          - "=========================================="
          - "✓ SUCCESS"
          - "VM: {{ inventory_hostname }}"
          - "Snapshot: '{{ snapshot_name }}' created"
          - "Storage: {{ vm_storage_gb }} GB"
          - "=========================================="
      when:
        - snapshot_result is defined
        - not (snapshot_result is failed)
        - snapshot_result.changed | default(false)

    - name: Report failure
      debug:
        msg:
          - "=========================================="
          - "✗ FAILED"
          - "VM: {{ inventory_hostname }}"
          - "Error: {{ snapshot_result.msg | default('Snapshot creation failed') }}"
          - "=========================================="
      when:
        - snapshot_result is defined
        - snapshot_result is failed

    - name: Report no change
      debug:
        msg:
          - "⊘ NO CHANGE - Snapshot may already exist"
      when:
        - snapshot_result is defined
        - not (snapshot_result is failed)
        - not (snapshot_result.changed | default(false))
