---
- name: VMware Snapshot Creation - WITH STORAGE VALIDATION
  hosts: all
  gather_facts: no
  connection: local
  
  vars:
    snapshot_name: "Snapshot for patching"
    snapshot_desc: "Created by Ansible via AWX for Patching Maintenance"
    
    vcenter_hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') }}"
    vcenter_username: "{{ lookup('env', 'VCENTER_USERNAME') }}"
    vcenter_password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"
    datacenter_name: "{{ lookup('env', 'VCENTER_DATACENTER') }}"
    
    # Timeout settings
    task_timeout: 60

  tasks:
    # -------------------------------------------------------------------------
    # STEP 0: VERIFY CONNECTIVITY
    # -------------------------------------------------------------------------
    - name: Test vCenter connectivity
      uri:
        url: "https://{{ vcenter_hostname }}/ui/"
        method: GET
        validate_certs: no
        timeout: 10
      delegate_to: localhost
      register: vcenter_test
      failed_when: false
      ignore_errors: yes

    - name: Display connectivity status
      debug:
        msg: "vCenter connectivity: {{ 'OK' if vcenter_test.status == 200 else 'FAILED - Check hostname/network' }}"

    - name: Fail if vCenter is unreachable
      fail:
        msg: "Cannot reach vCenter at {{ vcenter_hostname }}"
      when: vcenter_test.failed | default(true)

    # -------------------------------------------------------------------------
    # STEP 1: GET VM BASIC INFO WITH TIMEOUT
    # -------------------------------------------------------------------------
    - name: Get VM information
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        name: "{{ inventory_hostname }}"
      delegate_to: localhost
      register: vm_info
      async: "{{ task_timeout }}"
      poll: 5

    - name: Check if VM info retrieval succeeded
      debug:
        msg: "VM info retrieved successfully for {{ inventory_hostname }}"

    - name: Fail if VM not found
      fail:
        msg: "VM {{ inventory_hostname }} not found in datacenter {{ datacenter_name }}"
      when: 
        - vm_info.instance is not defined
        - vm_info.failed | default(false)

    # -------------------------------------------------------------------------
    # STEP 2: EXTRACT VM STORAGE USAGE
    # -------------------------------------------------------------------------
    - name: Set VM basic facts
      set_fact:
        vm_moid: "{{ vm_info.instance.moid }}"
        is_powered_on: "{{ vm_info.instance.hw_power_status == 'poweredOn' }}"
        vm_datastore_list: "{{ vm_info.instance.hw_datastore }}"
        vm_disk_files: "{{ vm_info.instance.hw_files }}"

    - name: Calculate VM total storage usage
      set_fact:
        vm_storage_used_bytes: "{{ vm_disk_files | map(attribute='size') | sum }}"

    - name: Convert to GB
      set_fact:
        vm_storage_used_gb: "{{ (vm_storage_used_bytes | int / 1024 / 1024 / 1024) | round(2) }}"

    - name: Display VM storage info
      debug:
        msg:
          - "VM: {{ inventory_hostname }}"
          - "MOID: {{ vm_moid }}"
          - "Power: {{ 'ON' if is_powered_on else 'OFF' }}"
          - "Storage Used: {{ vm_storage_used_gb }} GB"
          - "Datastores: {{ vm_datastore_list | join(', ') }}"

    # -------------------------------------------------------------------------
    # STEP 3: GET DATASTORE FREE SPACE (ONE AT A TIME)
    # -------------------------------------------------------------------------
    - name: Get datastore free space for {{ item }}
      community.vmware.vmware_datastore_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        name: "{{ item }}"
      delegate_to: localhost
      register: datastore_info_result
      loop: "{{ vm_datastore_list }}"
      async: "{{ task_timeout }}"
      poll: 5
      retries: 2
      delay: 5
      until: datastore_info_result is succeeded

    # -------------------------------------------------------------------------
    # STEP 4: BUILD DATASTORE COMPARISON
    # -------------------------------------------------------------------------
    - name: Build datastore details
      set_fact:
        datastore_details: >-
          {{
            datastore_details | default([]) + [{
              'name': item.datastores[0].name,
              'capacity_gb': (item.datastores[0].capacity / 1024 / 1024 / 1024) | round(2),
              'free_space_gb': (item.datastores[0].freeSpace / 1024 / 1024 / 1024) | round(2),
              'free_percent': ((item.datastores[0].freeSpace / item.datastores[0].capacity * 100) | round(2)),
              'has_sufficient_space': (item.datastores[0].freeSpace / 1024 / 1024 / 1024) > (vm_storage_used_gb | float)
            }]
          }}
      loop: "{{ datastore_info_result.results }}"
      when: 
        - item.datastores is defined 
        - item.datastores | length > 0
        - not (item.failed | default(false))

    # -------------------------------------------------------------------------
    # STEP 5: VALIDATE STORAGE CAPACITY
    # -------------------------------------------------------------------------
    - name: Check if any datastore has sufficient space
      set_fact:
        can_create_snapshot: >-
          {{
            (datastore_details | default([]) | selectattr('has_sufficient_space', 'equalto', true) | list | length > 0)
          }}
        sufficient_datastores: >-
          {{
            datastore_details | default([]) | selectattr('has_sufficient_space', 'equalto', true) | list
          }}
        insufficient_datastores: >-
          {{
            datastore_details | default([]) | selectattr('has_sufficient_space', 'equalto', false) | list
          }}

    # -------------------------------------------------------------------------
    # STEP 6: DISPLAY VALIDATION RESULTS
    # -------------------------------------------------------------------------
    - name: Display storage validation
      debug:
        msg:
          - "=========================================="
          - "STORAGE VALIDATION RESULTS"
          - "=========================================="
          - "VM                : {{ inventory_hostname }}"
          - "VM Storage Used   : {{ vm_storage_used_gb }} GB"
          - "Power State       : {{ 'ON' if is_powered_on else 'OFF' }}"
          - ""
          - "DATASTORE ANALYSIS:"
          - "{% for ds in datastore_details | default([]) %}-----------------------------------
{{ ds.name }}:
  Total     : {{ ds.capacity_gb }} GB
  Free      : {{ ds.free_space_gb }} GB ({{ ds.free_percent }}%)
  Status    : {{ 'SUFFICIENT ✓' if ds.has_sufficient_space else 'INSUFFICIENT ✗' }}
  Reason    : {{ 'Free (' + (ds.free_space_gb | string) + ' GB) > Used (' + (vm_storage_used_gb | string) + ' GB)' if ds.has_sufficient_space else 'Free (' + (ds.free_space_gb | string) + ' GB) < Used (' + (vm_storage_used_gb | string) + ' GB)' }}{% if not loop.last %}

{% endif %}{% endfor %}"
          - "=========================================="
          - "DECISION          : {{ 'CREATE SNAPSHOT ✓' if (can_create_snapshot and is_powered_on) else 'SKIP SNAPSHOT ✗' }}"
          - "{% if not is_powered_on %}REASON            : VM is powered off{% elif not can_create_snapshot %}REASON            : No datastore has sufficient free space{% endif %}"
          - "=========================================="

    # -------------------------------------------------------------------------
    # STEP 7: CREATE SNAPSHOT IF VALIDATION PASSES
    # -------------------------------------------------------------------------
    - name: Create VM snapshot
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        moid: "{{ vm_moid }}"
        state: present
        snapshot_name: "{{ snapshot_name }}"
        description: "{{ snapshot_desc }}"
        quiesce: no
        memory_dump: no
      delegate_to: localhost
      when:
        - is_powered_on
        - can_create_snapshot | bool
      register: snapshot_result
      async: 300
      poll: 10

    # -------------------------------------------------------------------------
    # STEP 8: REPORT RESULTS
    # -------------------------------------------------------------------------
    - name: Report SUCCESS
      debug:
        msg:
          - "=========================================="
          - "✓✓✓ SNAPSHOT CREATED ✓✓✓"
          - "=========================================="
          - "VM            : {{ inventory_hostname }}"
          - "Snapshot      : {{ snapshot_name }}"
          - "Storage Used  : {{ vm_storage_used_gb }} GB"
          - ""
          - "Datastores with sufficient space:"
          - "{% for ds in sufficient_datastores %}  ✓ {{ ds.name }}: {{ ds.free_space_gb }} GB free{% if not loop.last %}
{% endif %}{% endfor %}"
          - "=========================================="
      when:
        - snapshot_result is defined
        - snapshot_result.changed | default(false)

    - name: Report SKIPPED - Insufficient Storage
      debug:
        msg:
          - "=========================================="
          - "⊘ SKIPPED - INSUFFICIENT STORAGE"
          - "=========================================="
          - "VM            : {{ inventory_hostname }}"
          - "Storage Used  : {{ vm_storage_used_gb }} GB"
          - ""
          - "{% for ds in insufficient_datastores | default([]) %}  ✗ {{ ds.name }}: {{ ds.free_space_gb }} GB free (need > {{ vm_storage_used_gb }} GB){% if not loop.last %}
{% endif %}{% endfor %}"
          - "=========================================="
      when:
        - is_powered_on
        - not (can_create_snapshot | bool)

    - name: Report SKIPPED - VM Powered Off
      debug:
        msg:
          - "=========================================="
          - "⊘ SKIPPED - VM POWERED OFF"
          - "=========================================="
          - "VM            : {{ inventory_hostname }}"
          - "=========================================="
      when: not is_powered_on

    - name: Report FAILED
      debug:
        msg:
          - "=========================================="
          - "✗ SNAPSHOT CREATION FAILED"
          - "=========================================="
          - "VM            : {{ inventory_hostname }}"
          - "Error         : {{ snapshot_result.msg | default('Unknown error') }}"
          - "=========================================="
      when:
        - snapshot_result is defined
        - snapshot_result.failed | default(false)
