---
- name: VMware Snapshot Creation - WITH STORAGE VALIDATION
  hosts: all
  gather_facts: no
  connection: local
  
  vars:
    snapshot_name: "Snapshot for patching"
    snapshot_desc: "Created by Ansible via AWX for Patching Maintenance"
    
    vcenter_hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') }}"
    vcenter_username: "{{ lookup('env', 'VCENTER_USERNAME') }}"
    vcenter_password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"
    datacenter_name: "{{ lookup('env', 'VCENTER_DATACENTER') }}"

  tasks:
    # -------------------------------------------------------------------------
    # STEP 1: GET VM INFO (INCLUDING DATASTORE DETAILS)
    # -------------------------------------------------------------------------
    - name: Get VM information with datastore details
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        name: "{{ inventory_hostname }}"
        schema: vsphere
        properties:
          - name
          - config.hardware.memoryMB
          - runtime.powerState
          - summary.storage
          - datastore
      delegate_to: localhost
      register: vm_info
      failed_when: false
      timeout: 30

    - name: Check if VM info was retrieved successfully
      fail:
        msg: "Failed to retrieve VM information for {{ inventory_hostname }}"
      when: vm_info.failed | default(false)

    # -------------------------------------------------------------------------
    # STEP 2: EXTRACT VM STORAGE AND DATASTORE INFO
    # -------------------------------------------------------------------------
    - name: Set VM basic facts
      set_fact:
        vm_moid: "{{ vm_info.instance.moid | default(vm_info.instance.obj._moId) }}"
        is_powered_on: "{{ vm_info.instance.hw_power_status == 'poweredOn' or vm_info.instance.runtime.powerState == 'poweredOn' }}"
        vm_storage_committed_bytes: "{{ vm_info.instance.summary.storage.committed | default(0) }}"
        vm_storage_uncommitted_bytes: "{{ vm_info.instance.summary.storage.uncommitted | default(0) }}"

    - name: Calculate VM storage in GB
      set_fact:
        vm_storage_used_gb: "{{ (vm_storage_committed_bytes | int / 1024 / 1024 / 1024) | round(2) }}"
        vm_storage_total_gb: "{{ ((vm_storage_committed_bytes | int + vm_storage_uncommitted_bytes | int) / 1024 / 1024 / 1024) | round(2) }}"

    # -------------------------------------------------------------------------
    # STEP 3: GET DATASTORE INFORMATION FROM VM OBJECT
    # -------------------------------------------------------------------------
    - name: Extract datastore information from VM
      set_fact:
        datastore_details: >-
          {{
            datastore_details | default([]) + [{
              'name': item.name,
              'capacity_gb': ((item.summary.capacity | default(0)) / 1024 / 1024 / 1024) | round(2),
              'free_space_gb': ((item.summary.freeSpace | default(0)) / 1024 / 1024 / 1024) | round(2),
              'free_percent': (((item.summary.freeSpace | default(0)) / (item.summary.capacity | default(1)) * 100) | round(2)),
              'has_sufficient_space': ((item.summary.freeSpace | default(0)) / 1024 / 1024 / 1024) > (vm_storage_used_gb | float)
            }]
          }}
      loop: "{{ vm_info.instance.datastore }}"
      when: 
        - vm_info.instance.datastore is defined
        - vm_info.instance.datastore | length > 0

    # -------------------------------------------------------------------------
    # STEP 4: DETERMINE IF ANY DATASTORE HAS SUFFICIENT SPACE
    # -------------------------------------------------------------------------
    - name: Check if any datastore has sufficient free space
      set_fact:
        can_create_snapshot: >-
          {{
            (datastore_details | default([]) | selectattr('has_sufficient_space', 'equalto', true) | list | length > 0)
          }}
        sufficient_datastores: >-
          {{
            datastore_details | default([]) | selectattr('has_sufficient_space', 'equalto', true) | list
          }}
        insufficient_datastores: >-
          {{
            datastore_details | default([]) | selectattr('has_sufficient_space', 'equalto', false) | list
          }}

    # -------------------------------------------------------------------------
    # STEP 5: DISPLAY PRE-FLIGHT STATUS
    # -------------------------------------------------------------------------
    - name: Display storage validation results
      debug:
        msg:
          - "=========================================="
          - "VM INFORMATION"
          - "=========================================="
          - "VM Name       : {{ inventory_hostname }}"
          - "MOID          : {{ vm_moid }}"
          - "Power State   : {{ 'Powered On' if is_powered_on else 'Powered Off' }}"
          - "Storage Used  : {{ vm_storage_used_gb }} GB (committed)"
          - "Storage Total : {{ vm_storage_total_gb }} GB (committed + uncommitted)"
          - "=========================================="
          - "DATASTORE ANALYSIS"
          - "=========================================="
          - "{% for ds in datastore_details | default([]) %}{{ ds.name }}:
  Capacity    : {{ ds.capacity_gb }} GB
  Free        : {{ ds.free_space_gb }} GB ({{ ds.free_percent }}%)
  Sufficient  : {{ '✓ YES' if ds.has_sufficient_space else '✗ NO' }} (Need > {{ vm_storage_used_gb }} GB){% if not loop.last %}

{% endif %}{% endfor %}"
          - "=========================================="
          - "VALIDATION RESULT"
          - "=========================================="
          - "Can Create    : {{ '✓ YES' if can_create_snapshot and is_powered_on else '✗ NO' }}"
          - "{% if not is_powered_on %}Reason        : VM is powered off{% elif not can_create_snapshot %}Reason        : No datastore has free space > {{ vm_storage_used_gb }} GB{% endif %}"
          - "=========================================="

    # -------------------------------------------------------------------------
    # STEP 6: CREATE SNAPSHOT (ONLY IF VALIDATION PASSES)
    # -------------------------------------------------------------------------
    - name: Create VM snapshot using MOID
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        moid: "{{ vm_moid }}"
        state: present
        snapshot_name: "{{ snapshot_name }}"
        description: "{{ snapshot_desc }}"
        quiesce: no
        memory_dump: no
      delegate_to: localhost
      when:
        - is_powered_on
        - can_create_snapshot | bool
      register: snapshot_result
      failed_when: false
      timeout: 300

    # -------------------------------------------------------------------------
    # STEP 7: REPORT RESULTS
    # -------------------------------------------------------------------------
    - name: Report snapshot creation success
      debug:
        msg:
          - "=========================================="
          - "✓ SUCCESS"
          - "Snapshot '{{ snapshot_name }}' created for {{ inventory_hostname }}"
          - "Datastores with sufficient space:"
          - "{% for ds in sufficient_datastores | default([]) %}  - {{ ds.name }}: {{ ds.free_space_gb }} GB free{% if not loop.last %}
{% endif %}{% endfor %}"
          - "=========================================="
      when:
        - snapshot_result is defined
        - snapshot_result.changed | default(false)
        - not (snapshot_result.failed | default(false))

    - name: Report insufficient storage
      debug:
        msg:
          - "=========================================="
          - "⊘ SKIPPED - INSUFFICIENT STORAGE"
          - "{{ inventory_hostname }}"
          - "VM Storage Used: {{ vm_storage_used_gb }} GB"
          - ""
          - "No datastore has free space greater than VM usage:"
          - "{% for ds in datastore_details | default([]) %}  - {{ ds.name }}: {{ ds.free_space_gb }} GB free (Need > {{ vm_storage_used_gb }} GB){% if not loop.last %}
{% endif %}{% endfor %}"
          - "=========================================="
      when:
        - is_powered_on
        - not (can_create_snapshot | bool)

    - name: Report skipped (VM powered off)
      debug:
        msg:
          - "=========================================="
          - "⊘ SKIPPED"
          - "{{ inventory_hostname }} is powered off"
          - "=========================================="
      when: not is_powered_on

    - name: Report snapshot creation failure
      debug:
        msg:
          - "=========================================="
          - "✗ FAILED"
          - "Could not create snapshot for {{ inventory_hostname }}"
          - "Error: {{ snapshot_result.msg | default('Unknown error') }}"
          - "=========================================="
      when:
        - snapshot_result is defined
        - snapshot_result.failed | default(false)
