---
- name: VMware Snapshot Creation with Storage Validation
  hosts: all
  gather_facts: no
  connection: local
  serial: 5
  
  vars:
    snapshot_name: "Snapshot for patching"
    snapshot_desc: "Created by Ansible via AWX for Patching Maintenance"
    safety_margin_gb: 10
    
    vcenter_hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') }}"
    vcenter_username: "{{ lookup('env', 'VCENTER_USERNAME') }}"
    vcenter_password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"
    datacenter_name: "{{ lookup('env', 'VCENTER_DATACENTER') }}"

  tasks:
    # -------------------------------------------------------------------------
    # STEP 1: GET VM INFO WITH VSPHERE SCHEMA
    # -------------------------------------------------------------------------
    - name: Get VM information with vSphere schema
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        name: "{{ inventory_hostname }}"
        schema: vsphere
      delegate_to: localhost
      register: vm_info
      ignore_errors: yes

    - name: Check VM info retrieval
      block:
        - debug:
            msg: "✗ Failed to retrieve VM info for {{ inventory_hostname }}"
        - meta: end_host
      when: vm_info is failed or vm_info.instance is not defined

    # -------------------------------------------------------------------------
    # STEP 2: EXTRACT VM BASIC INFO
    # -------------------------------------------------------------------------
    - name: Set VM basic facts
      set_fact:
        vm_moid: "{{ vm_info.instance._vimref.split(':')[1] }}"
        vm_name: "{{ vm_info.instance.name }}"
        vm_power_state: "{{ vm_info.instance.runtime.powerState }}"
        is_powered_on: "{{ vm_info.instance.runtime.powerState == 'poweredOn' }}"

    - name: Display VM basic info
      debug:
        msg:
          - "VM: {{ vm_name }}"
          - "MOID: {{ vm_moid }}"
          - "Power: {{ vm_power_state }}"

    # Check power state
    - name: Skip if powered off
      block:
        - debug:
            msg: "⊘ SKIPPED: {{ vm_name }} is powered off"
        - meta: end_host
      when: not is_powered_on

    # -------------------------------------------------------------------------
    # STEP 3: DEBUG - EXAMINE SCHEMA STRUCTURE
    # -------------------------------------------------------------------------
    - name: DEBUG - Display vm_info.instance.datastore structure
      debug:
        var: vm_info.instance.datastore
      when: vm_info.instance.datastore is defined

    - name: DEBUG - Display vm_info.instance.storage structure
      debug:
        var: vm_info.instance.storage
      when: vm_info.instance.storage is defined

    - name: DEBUG - Display vm_info.instance.storage.perDatastoreUsage
      debug:
        var: vm_info.instance.storage.perDatastoreUsage
      when: vm_info.instance.storage is defined and vm_info.instance.storage.perDatastoreUsage is defined

    # -------------------------------------------------------------------------
    # STEP 4: EXTRACT STORAGE INFO FROM VSPHERE DATA
    # -------------------------------------------------------------------------
    - name: Check if storage info is available
      set_fact:
        has_storage_info: "{{ vm_info.instance.storage is defined and vm_info.instance.storage.perDatastoreUsage is defined }}"

    - name: Extract VM storage per datastore information
      set_fact:
        vm_storage_per_ds: "{{ vm_info.instance.storage.perDatastoreUsage | default([]) }}"
      when: has_storage_info

    - name: Use fallback if storage info unavailable
      set_fact:
        vm_storage_per_ds: []
        skip_space_check: true
      when: not has_storage_info

    - name: Display VM storage per datastore
      debug:
        msg: "VM uses {{ vm_storage_per_ds | length }} datastore(s)"

    # -------------------------------------------------------------------------
    # STEP 5: GET DATASTORE DETAILS
    # -------------------------------------------------------------------------
    - name: Get all datastores in datacenter
      community.vmware.vmware_datastore_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
      delegate_to: localhost
      register: all_datastores_info
      ignore_errors: yes

    - name: Check datastore info retrieval
      set_fact:
        skip_space_check: true
      when: all_datastores_info is failed or all_datastores_info.datastores is not defined

    # -------------------------------------------------------------------------
    # STEP 6: DEBUG - EXAMINE DATASTORE INFO STRUCTURE
    # -------------------------------------------------------------------------
    - name: DEBUG - Display all_datastores_info.datastores structure (first item)
      debug:
        msg: "{{ all_datastores_info.datastores[0] }}"
      when: 
        - all_datastores_info.datastores is defined
        - all_datastores_info.datastores | length > 0

    - name: DEBUG - Display datastore names
      debug:
        msg: "{{ all_datastores_info.datastores | map(attribute='name') | list }}"
      when: all_datastores_info.datastores is defined

    - name: DEBUG - Display vm_info.instance.datastore type
      debug:
        msg: 
          - "Type: {{ vm_info.instance.datastore | type_debug }}"
          - "Content: {{ vm_info.instance.datastore }}"
      when: vm_info.instance.datastore is defined

    # -------------------------------------------------------------------------
    # STEP 7: PAUSE FOR ANALYSIS
    # -------------------------------------------------------------------------
    - name: PAUSE - Review debug output above
      debug:
        msg:
          - "=========================================="
          - "REVIEW THE DEBUG OUTPUT ABOVE"
          - "=========================================="
          - "Check the structure of:"
          - "1. vm_info.instance.datastore"
          - "2. vm_info.instance.storage.perDatastoreUsage"
          - "3. all_datastores_info.datastores"
          - "=========================================="
          - "After reviewing, update the playbook with correct attribute names"
          - "=========================================="

    # -------------------------------------------------------------------------
    # STEP 8: STOP HERE FOR NOW (Remove this block once schema is understood)
    # -------------------------------------------------------------------------
    - name: Stop execution for schema analysis
      meta: end_host
