---
- name: VMware Snapshot Creation - OPTIMAL SOLUTION
  hosts: all
  gather_facts: no
  connection: local
 
  vars:
    snapshot_name: "Snapshot for patching"
    snapshot_desc: "Created by Ansible via AWX for Patching Maintenance"
    vcenter_hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') }}"
    vcenter_username: "{{ lookup('env', 'VCENTER_USERNAME') }}"
    vcenter_password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"
    datacenter_name: "{{ lookup('env', 'VCENTER_DATACENTER') }}"
 
  tasks:
 
    # -------------------------------------------------------------------------
    # STEP 1: GET VM INFO (INCLUDING MOID)
    # -------------------------------------------------------------------------
    - name: Get VM information
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        name: "{{ inventory_hostname }}"
      delegate_to: localhost
      register: vm_info
 
    # -------------------------------------------------------------------------
    # STEP 2: GET DATASTORE INFO
    # -------------------------------------------------------------------------
    - name: Get datastore information
      community.vmware.vmware_datastore_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
      delegate_to: localhost
      register: ds_info
 
    # -------------------------------------------------------------------------
    # STEP 3: EXTRACT VM + DATASTORE FACTS
    # -------------------------------------------------------------------------
    - name: Set VM facts
      set_fact:
        vm_moid: "{{ vm_info.instance.moid }}"
        is_powered_on: "{{ vm_info.instance.hw_power_status == 'poweredOn' }}"
        vm_storage_bytes: "{{ vm_info.instance.hw_files | map(attribute='size') | sum }}"
        vm_datastore_name: "{{ vm_info.instance.hw_datastore[0] }}"
 
    - name: Calculate VM storage in GB for display
      set_fact:
        vm_storage_gb: "{{ (vm_storage_bytes | int / 1024 / 1024 / 1024) | round(2) }}"
 
    - name: Get datastore free space
      set_fact:
        datastore_free_bytes: >-
          {{ (ds_info.datastores
              | selectattr('name', 'equalto', vm_info.instance.hw_datastore[0])
              | first).freeSpace }}
 
    - name: Determine if datastore has enough space
      set_fact:
        has_enough_space: "{{ datastore_free_bytes | int > vm_storage_bytes | int }}"
 
    - name: Display pre-flight status
      debug:
        msg:
          - "=========================================="
          - "VM            : {{ inventory_hostname }}"
          - "MOID          : {{ vm_moid }}"
          - "Power State   : {{ vm_info.instance.hw_power_status }}"
          - "Datastore     : {{ vm_datastore_name }}"
          - "VM Storage    : {{ vm_storage_gb }} GB"
          - "Datastore Free: {{ (datastore_free_bytes | int / 1024 / 1024 / 1024) | round(2) }} GB"
          - "Enough Space? : {{ 'YES ✓' if has_enough_space else 'NO ✗ - Insufficient datastore space' }}"
          - "Ready         : {{ 'YES ✓' if is_powered_on and has_enough_space else 'NO ✗' }}"
          - "=========================================="
 
    # -------------------------------------------------------------------------
    # STEP 4: CREATE SNAPSHOT ONLY IF POWERED ON + ENOUGH SPACE
    # -------------------------------------------------------------------------
    - name: Create VM snapshot using MOID
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        moid: "{{ vm_moid }}"
        state: present
        snapshot_name: "{{ snapshot_name }}"
        description: "{{ snapshot_desc }}"
        quiesce: no
        memory_dump: no
      delegate_to: localhost
      when:
        - is_powered_on
        - has_enough_space
      register: snapshot_result
 
    # -------------------------------------------------------------------------
    # STEP 5: REPORT RESULTS (SINGLE CONSOLIDATED BLOCK)
    # -------------------------------------------------------------------------
    - name: Set snapshot status message
      set_fact:
        snapshot_status: >-
          {% if snapshot_result is defined and snapshot_result.changed %}
          ✓ SUCCESS - Snapshot '{{ snapshot_name }}' created for {{ inventory_hostname }}
          {% elif snapshot_result is defined and snapshot_result.failed | default(false) %}
          ✗ FAILED - Could not create snapshot for {{ inventory_hostname }}
          Error: {{ snapshot_result.msg | default('Unknown error') }}
          {% elif not is_powered_on and not has_enough_space %}
          ⊘ SKIPPED - VM powered off AND insufficient datastore space
          {% elif not is_powered_on %}
          ⊘ SKIPPED - VM powered off
          {% elif not has_enough_space %}
          ⊘ SKIPPED - Insufficient datastore space
          {% else %}
          ⊘ SKIPPED - Unknown condition
          {% endif %}
 
    - name: Report snapshot status
      debug:
        msg:
          - "=========================================="
          - "{{ snapshot_status }}"
          - "VM Name       : {{ inventory_hostname }}"
          - "Power State   : {{ vm_info.instance.hw_power_status }}"
          - "VM Size       : {{ vm_storage_gb }} GB"
          - "Datastore     : {{ vm_datastore_name }}"
          - "Free Space    : {{ (datastore_free_bytes | int / 1024 / 1024 / 1024) | round(2) }} GB"
          - "=========================================="
