---
- name: VMware Snapshot Creation with Storage Validation (AWX Optimized)
  hosts: all
  gather_facts: no
  connection: local
  serial: 5  # Process 5 VMs at a time to avoid overwhelming vCenter
  
  vars:
    snapshot_name: "Snapshot for patching"
    snapshot_desc: "Created by Ansible via AWX for Patching Maintenance"
    safety_margin_gb: 10
    timeout_seconds: 300
    
    vcenter_hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') }}"
    vcenter_username: "{{ lookup('env', 'VCENTER_USERNAME') }}"
    vcenter_password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"
    datacenter_name: "{{ lookup('env', 'VCENTER_DATACENTER') }}"

  tasks:
    # -------------------------------------------------------------------------
    # INITIALIZATION
    # -------------------------------------------------------------------------
    - name: "=== Processing VM: {{ inventory_hostname }} ==="
      debug:
        msg: "Starting snapshot workflow for {{ inventory_hostname }}"

    # -------------------------------------------------------------------------
    # STEP 1: GET VM INFO (WITH TIMEOUT)
    # -------------------------------------------------------------------------
    - name: Get VM information
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        name: "{{ inventory_hostname }}"
      delegate_to: localhost
      register: vm_info
      async: "{{ timeout_seconds }}"
      poll: 5
      ignore_errors: yes

    - name: Check if VM info was retrieved
      fail:
        msg: "Failed to get VM information for {{ inventory_hostname }}"
      when: 
        - vm_info is failed or vm_info.instance is not defined
      ignore_errors: yes
      register: vm_info_check

    - name: Skip host if VM info failed
      meta: end_host
      when: vm_info_check is failed

    # -------------------------------------------------------------------------
    # STEP 2: EXTRACT AND VALIDATE BASIC INFO
    # -------------------------------------------------------------------------
    - name: Extract VM properties
      set_fact:
        vm_moid: "{{ vm_info.instance.moid | default('unknown') }}"
        vm_power_state: "{{ vm_info.instance.hw_power_status | default('unknown') }}"
        is_powered_on: "{{ vm_info.instance.hw_power_status == 'poweredOn' }}"
        vm_datastores: "{{ vm_info.instance.hw_datastore | default([]) }}"

    - name: Display VM status
      debug:
        msg:
          - "VM Name        : {{ inventory_hostname }}"
          - "MOID           : {{ vm_moid }}"
          - "Power State    : {{ vm_power_state }}"
          - "Datastores     : {{ vm_datastores | join(', ') if vm_datastores else 'None found' }}"

    # -------------------------------------------------------------------------
    # STEP 3: POWER STATE CHECK
    # -------------------------------------------------------------------------
    - name: Check if VM is powered on
      block:
        - debug:
            msg: "⊘ SKIPPED: {{ inventory_hostname }} is not powered on (State: {{ vm_power_state }})"
        - meta: end_host
      when: not is_powered_on

    # -------------------------------------------------------------------------
    # STEP 4: GET DATASTORE INFORMATION
    # -------------------------------------------------------------------------
    - name: Get all datastores in datacenter
      community.vmware.vmware_datastore_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
      delegate_to: localhost
      register: datastore_info
      async: "{{ timeout_seconds }}"
      poll: 5
      ignore_errors: yes

    - name: Set space check skip flag if datastore info failed
      set_fact:
        skip_space_check: true
      when: datastore_info is failed or datastore_info.datastores is not defined

    # -------------------------------------------------------------------------
    # STEP 5: ANALYZE DATASTORE SPACE
    # -------------------------------------------------------------------------
    - name: Analyze datastore space availability
      block:
        - name: Filter relevant datastores
          set_fact:
            relevant_datastores: "{{ datastore_info.datastores | selectattr('name', 'in', vm_datastores) | list }}"

        - name: Calculate space for each datastore
          set_fact:
            datastore_space_check: "{{ datastore_space_check | default([]) + [{'name': item.name, 'free_gb': (item.freeSpace / 1073741824) | round(2), 'capacity_gb': (item.capacity / 1073741824) | round(2), 'has_sufficient_space': (item.freeSpace / 1073741824) > 150}] }}"
          loop: "{{ relevant_datastores }}"
          loop_control:
            label: "{{ item.name }}"

        - name: Display datastore analysis
          debug:
            msg:
              - "Datastore Space Analysis:"
              - "{% for ds in datastore_space_check %}"
              - "  {{ ds.name }}: {{ ds.free_gb }} GB free / {{ ds.capacity_gb }} GB total - {{ 'OK' if ds.has_sufficient_space else 'LOW' }}"
              - "{% endfor %}"

        - name: Determine if snapshot can proceed
          set_fact:
            can_create_snapshot: "{{ datastore_space_check | selectattr('has_sufficient_space', 'equalto', true) | list | length > 0 }}"

        - name: Skip if insufficient space
          block:
            - debug:
                msg: "⊘ SKIPPED: No datastore has sufficient free space (need ~150GB + margin)"
            - meta: end_host
          when: not can_create_snapshot

      when: not (skip_space_check | default(false))

    - name: Bypass space check warning
      debug:
        msg: "⚠ WARNING: Datastore space check skipped, proceeding with snapshot creation"
      when: skip_space_check | default(false)

    # -------------------------------------------------------------------------
    # STEP 6: CREATE SNAPSHOT
    # -------------------------------------------------------------------------
    - name: Create VM snapshot
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        moid: "{{ vm_moid }}"
        state: present
        snapshot_name: "{{ snapshot_name }}"
        description: "{{ snapshot_desc }}"
        quiesce: no
        memory_dump: no
      delegate_to: localhost
      register: snapshot_result
      async: "{{ timeout_seconds }}"
      poll: 10
      ignore_errors: yes

    # -------------------------------------------------------------------------
    # STEP 7: REPORT RESULTS
    # -------------------------------------------------------------------------
    - name: Report snapshot success
      debug:
        msg:
          - "=========================================="
          - "✓ SUCCESS"
          - "VM: {{ inventory_hostname }}"
          - "Snapshot: {{ snapshot_name }}"
          - "Time: {{ ansible_date_time.iso8601 | default('timestamp unavailable') }}"
          - "=========================================="
      when: 
        - snapshot_result is defined
        - snapshot_result is not failed
        - snapshot_result.changed | default(false)

    - name: Report snapshot failure
      debug:
        msg:
          - "=========================================="
          - "✗ FAILED"
          - "VM: {{ inventory_hostname }}"
          - "Error: {{ snapshot_result.msg | default('Snapshot task failed or timed out') }}"
          - "=========================================="
      when:
        - snapshot_result is defined
        - snapshot_result is failed

    - name: Report snapshot no change
      debug:
        msg:
          - "=========================================="
          - "⊘ NO CHANGE"
          - "VM: {{ inventory_hostname }}"
          - "Snapshot may already exist or task returned no change"
          - "=========================================="
      when:
        - snapshot_result is defined
        - snapshot_result is not failed
        - not (snapshot_result.changed | default(false))

    # -------------------------------------------------------------------------
    # CLEANUP
    # -------------------------------------------------------------------------
    - name: Mark host processing complete
      debug:
        msg: "Completed processing {{ inventory_hostname }}"
