---
- name: VMware Snapshot Creation - AWX OPTIMIZED
  hosts: all
  gather_facts: no
  connection: local

  vars:
    snapshot_name: "{{ snapshot_name | default('Pre-Patch-Snapshot') }}"
    snapshot_desc: "{{ snapshot_desc | default('Created by Ansible AWX for Maintenance') }}"
    vcenter_hostname: "{{ vcenter_hostname | default(lookup('env', 'VCENTER_HOSTNAME')) }}"
    vcenter_username: "{{ vcenter_username | default(lookup('env', 'VCENTER_USERNAME')) }}"
    vcenter_password: "{{ vcenter_password | default(lookup('env', 'VCENTER_PASSWORD')) }}"
    datacenter_name: "{{ datacenter_name | default(lookup('env', 'VCENTER_DATACENTER')) }}"
    # Space buffer percentage (20% recommended for snapshots)
    space_buffer_pct: 1.2

  tasks:
    # -------------------------------------------------------------------------
    # STEP 1: VALIDATE INPUTS (Important for AWX)
    # -------------------------------------------------------------------------
    - name: Validate required variables
      fail:
        msg: |
          Missing required variable: {{ item }}
          Set in AWX as:
          - Extra Variables OR
          - Survey OR
          - Environment Variables
      when: >
        (vcenter_hostname | default('')) == '' or
        (vcenter_username | default('')) == '' or
        (vcenter_password | default('')) == '' or
        (datacenter_name | default('')) == ''
      loop:
        - vcenter_hostname
        - vcenter_username
        - vcenter_password
        - datacenter_name
      run_once: yes

    # -------------------------------------------------------------------------
    # STEP 2: GET VM INFORMATION
    # -------------------------------------------------------------------------
    - name: Get VM information from vCenter
      vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        vm_id: "{{ inventory_hostname }}"
      delegate_to: localhost
      register: vm_info
      ignore_errors: yes
      failed_when: >
        vm_info.failed and 
        'not found' not in vm_info.msg | default('') and
        'Unable to find' not in vm_info.msg | default('')

    - name: Fail if VM not found
      fail:
        msg: "VM '{{ inventory_hostname }}' not found in vCenter {{ vcenter_hostname }}"
      when: vm_info.failed | default(false)

    - name: Extract VM facts
      set_fact:
        vm_moid: "{{ vm_info.virtual_machines[0].moid }}"
        vm_power_state: "{{ vm_info.virtual_machines[0].power_state }}"
        vm_storage_mb: "{{ vm_info.virtual_machines[0].disk_sizes | sum }}"
        vm_datastores: "{{ vm_info.virtual_machines[0].datastore }}"
        vm_guest_name: "{{ vm_info.virtual_machines[0].guest_name }}"
      when: vm_info.virtual_machines | length > 0

    # -------------------------------------------------------------------------
    # STEP 3: CHECK POWER STATE
    # -------------------------------------------------------------------------
    - name: Set power state fact
      set_fact:
        is_powered_on: "{{ vm_power_state == 'poweredOn' }}"

    # -------------------------------------------------------------------------
    # STEP 4: CHECK DATASTORE FREE SPACE
    # -------------------------------------------------------------------------
    - name: Get datastore information
      vmware_datastore_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
      delegate_to: localhost
      register: ds_info
      when: vm_datastores is defined

    - name: Calculate required space with buffer
      set_fact:
        # Convert MB to bytes and add buffer
        required_space_bytes: "{{ ((vm_storage_mb | default(0) | int) * 1024 * 1024 * space_buffer_pct) | int }}"
        required_space_gb: "{{ (required_space_bytes / (1024*1024*1024)) | round(2) }}"
      when: vm_storage_mb is defined

    - name: Check datastore free space
      set_fact:
        has_enough_space: >-
          {% if vm_datastores is defined and vm_datastores %}
            {% set ns = namespace(found_space=false) %}
            {% for ds_name in vm_datastores %}
              {% set ds = ds_info.datastores | selectattr('name', 'equalto', ds_name) | first %}
              {% if ds %}
                {% set free_gb = (ds.free_space / (1024*1024*1024)) | round(2) %}
                {% set needed_gb = (required_space_bytes / (1024*1024*1024)) | round(2) %}
                {% if ds.free_space > required_space_bytes %}
                  {% set ns.found_space = true %}
                {% endif %}
              {% endif %}
            {% endfor %}
            {{ ns.found_space }}
          {% else %}
            false
          {% endif %}
      when: 
        - vm_datastores is defined
        - ds_info is defined
        - required_space_bytes is defined

    # -------------------------------------------------------------------------
    # STEP 5: PRE-FLIGHT SUMMARY (AWX Friendly Output)
    # -------------------------------------------------------------------------
    - name: Display pre-flight check results
      debug:
        msg: |
          ==========================================
          VM PRE-FLIGHT CHECK - {{ inventory_hostname }}
          ==========================================
          VM Name: {{ vm_guest_name | default(inventory_hostname) }}
          Power State: {{ vm_power_state }} ({{ '✓ READY' if is_powered_on else '✗ SKIP - Powered off' }})
          Total Storage: {{ vm_storage_mb | default(0) }} MB
          
          DATASTORE CHECK:
          {% if vm_datastores is defined and vm_datastores %}
            {% for ds_name in vm_datastores %}
            - {{ ds_name }}:
              {% set ds = ds_info.datastores | selectattr('name', 'equalto', ds_name) | first %}
              {% if ds %}
                Free: {{ (ds.free_space / (1024*1024*1024)) | round(2) }} GB
                Needed: {{ required_space_gb | default('N/A') }} GB (with {{ ((space_buffer_pct - 1) * 100) | int }}% buffer)
                Status: {{ '✓ SUFFICIENT' if ds.free_space > required_space_bytes else '✗ INSUFFICIENT' }}
              {% else %}
                ✗ NOT FOUND IN VCENTER
              {% endif %}
            {% endfor %}
          {% else %}
            ✗ NO DATASTORES FOUND
          {% endif %}
          
          OVERALL STATUS: {{ '✓ READY FOR SNAPSHOT' if is_powered_on and has_enough_space else '✗ NOT READY' }}
          ==========================================
      when: vm_info is defined and not vm_info.failed

    # -------------------------------------------------------------------------
    # STEP 6: CREATE SNAPSHOT (Only if conditions met)
    # -------------------------------------------------------------------------
    - name: Create VM snapshot
      vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        folder: "/"
        name: "{{ inventory_hostname }}"
        state: present
        snapshot_name: "{{ snapshot_name }}"
        description: "{{ snapshot_desc }}"
        quiesce: no
        memory_dump: no
      delegate_to: localhost
      register: snapshot_result
      when:
        - is_powered_on | default(false)
        - has_enough_space | default(false)
      ignore_errors: yes

    # -------------------------------------------------------------------------
    # STEP 7: POST-EXECUTION REPORTING
    # -------------------------------------------------------------------------
    - name: Record successful snapshot
      set_fact:
        snapshot_created: true
      when:
        - snapshot_result is defined
        - snapshot_result.changed

    - name: Display success message
      debug:
        msg: |
          ==========================================
          ✓ SNAPSHOT CREATION SUCCESSFUL
          VM: {{ inventory_hostname }}
          Snapshot: {{ snapshot_name }}
          Time: {{ ansible_date_time.iso8601 }}
          ==========================================
      when: snapshot_created | default(false)

    - name: Display failure message
      debug:
        msg: |
          ==========================================
          ✗ SNAPSHOT CREATION FAILED
          VM: {{ inventory_hostname }}
          Error: {{ snapshot_result.msg | default('Unknown error') }}
          ==========================================
      when:
        - snapshot_result is defined
        - snapshot_result.failed | default(false)

    - name: Display skip reasons
      debug:
        msg: |
          ==========================================
          ⚠ SNAPSHOT SKIPPED
          VM: {{ inventory_hostname }}
          Reason:
          {% if not (is_powered_on | default(false)) %}
          - VM is powered off ({{ vm_power_state }})
          {% endif %}
          {% if not (has_enough_space | default(false)) %}
          - Insufficient datastore space
          {% endif %}
          {% if not (is_powered_on | default(false)) and not (has_enough_space | default(false)) %}
          - Both: powered off AND insufficient space
          {% endif %}
          ==========================================
      when: not (is_powered_on | default(false) and has_enough_space | default(false))

    # -------------------------------------------------------------------------
    # STEP 8: FINAL SUMMARY FOR AWX JOB OUTPUT
    # -------------------------------------------------------------------------
    - name: Final job summary
      set_fact:
        job_summary: >-
          {% if snapshot_created | default(false) %}
          SUCCESS: Snapshot created for {{ inventory_hostname }}
          {% elif not is_powered_on | default(false) %}
          SKIPPED: {{ inventory_hostname }} is powered off
          {% elif not has_enough_space | default(false) %}
          SKIPPED: Insufficient datastore space for {{ inventory_hostname }}
          {% elif snapshot_result.failed | default(false) %}
          FAILED: {{ snapshot_result.msg | default('Unknown error') }}
          {% else %}
          UNKNOWN: No action taken for {{ inventory_hostname }}
          {% endif %}

    - name: Print final summary
      debug:
        msg: "{{ job_summary }}"
      run_once: yes
